// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7jWhnSX8rQVW6z9DBCduj2CeiEiMKVKY',
    appId: '1:957321509907:web:48f3927a9522c0163c53e6',
    messagingSenderId: '957321509907',
    projectId: 'kanjou-sard',
    authDomain: 'kanjou-sard.firebaseapp.com',
    storageBucket: 'kanjou-sard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnhLYNr88yy48vTYYIq6hpTjUs-ErbiE',
    appId: '1:957321509907:android:6039b9d141e09a343c53e6',
    messagingSenderId: '957321509907',
    projectId: 'kanjou-sard',
    storageBucket: 'kanjou-sard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhyqJDJ-nJXh69Xq4HoU03gJj0SgcnrU',
    appId: '1:957321509907:ios:a73904141ffcd4503c53e6',
    messagingSenderId: '957321509907',
    projectId: 'kanjou-sard',
    storageBucket: 'kanjou-sard.appspot.com',
    iosBundleId: 'com.example.notesAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWhyqJDJ-nJXh69Xq4HoU03gJj0SgcnrU',
    appId: '1:957321509907:ios:8cd28493be3b2a9b3c53e6',
    messagingSenderId: '957321509907',
    projectId: 'kanjou-sard',
    storageBucket: 'kanjou-sard.appspot.com',
    iosBundleId: 'com.example.notesAi.RunnerTests',
  );
}
