// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzENN77gP_dKhhn15Y6n2ajzgNsbG3dcU',
    appId: '1:333958828802:web:d59b2b63c9305d02ef681b',
    messagingSenderId: '333958828802',
    projectId: 'kanjou-app',
    authDomain: 'kanjou-app.firebaseapp.com',
    storageBucket: 'kanjou-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dKN8WZ6R_aTTsKO2D4-Azl5HeCLif60',
    appId: '1:333958828802:android:a80d68ec154f25d1ef681b',
    messagingSenderId: '333958828802',
    projectId: 'kanjou-app',
    storageBucket: 'kanjou-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDAh3hB36wCF836hHf9_pg27qJKjl7lI',
    appId: '1:333958828802:ios:ed63eee3cc0c2dfbef681b',
    messagingSenderId: '333958828802',
    projectId: 'kanjou-app',
    storageBucket: 'kanjou-app.appspot.com',
    iosBundleId: 'com.example.kanjou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfDAh3hB36wCF836hHf9_pg27qJKjl7lI',
    appId: '1:333958828802:ios:cf8e7c1e8175f061ef681b',
    messagingSenderId: '333958828802',
    projectId: 'kanjou-app',
    storageBucket: 'kanjou-app.appspot.com',
    iosBundleId: 'com.example.kanjou.RunnerTests',
  );
}
